import{C as l,i as a,S as u}from"./assets/vendor-C0crhc5E.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function e(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=e(r);fetch(r.href,o)}})();const L=()=>{const n=localStorage.getItem("encrypted_api_key");if(!n)return console.error("Encrypted API key не найден"),null;const e=l.AES.decrypt(n,"your-secret-passphrase").toString(l.enc.Utf8);return e||(console.error("Ошибка расшифровки API ключа"),null)},m=async n=>{const t=L();if(!t)return console.error("API ключ отсутствует"),[];const e="https://pixabay.com/api/";try{const s=`${e}?key=${t}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;console.log("Запрос к API:",s);const r=await fetch(s);if(!r.ok)throw new Error(`Ошибка при получении данных: ${r.statusText}`);const o=await r.json();if(console.log("Полученные данные:",o),!o.hits||o.hits.length===0)throw new Error("No images found");return o.hits}catch(s){return console.error(s),[]}},y=n=>{const t=document.querySelector(".gallery");if(t.innerHTML="",console.log("Изображения для отображения:",n),n.length===0){t.innerHTML="<p>No images found</p>";return}const e=n.map(({webformatURL:s,largeImageURL:r,tags:o,likes:c,views:g,comments:p,downloads:h})=>`
      <div class="card">
        <a href="${r}">
          <img src="${s}" alt="${o||"Image"}" />
        </a>
        <p>Likes: ${c} | Views: ${g} | Comments: ${p} | Downloads: ${h}</p>
      </div>
    `).join("");t.insertAdjacentHTML("beforeend",e)},d=document.querySelector("#search-form"),f=document.querySelector(".search-input"),i=document.querySelector(".gallery");d?d.addEventListener("submit",async n=>{n.preventDefault();const t=f.value.trim();if(!t){a.error({message:"Please enter a search term"});return}const e=document.createElement("div");e.classList.add("loader"),e.textContent="Loading...",i.innerHTML="",i.appendChild(e);try{const s=await m(t);s.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!"}):(y(s),new u(".gallery a"))}catch{a.error({message:"Something went wrong, please try again!"})}finally{e&&e.remove()}}):console.log('Элемент с id "search-form" не найден');document.querySelector(".load-more").addEventListener("click",async()=>{const n=f.value.trim();if(!n){a.error({message:"Please enter a search term"});return}const t=document.createElement("div");t.classList.add("loader"),t.textContent="Loading...",i.appendChild(t);try{const e=await m(n);e.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!"}):(y(e),new u(".gallery a"))}catch{a.error({message:"Something went wrong, please try again!"})}finally{const e=document.querySelector(".loader");e&&e.remove()}});
//# sourceMappingURL=index.js.map
