import{i as a,S as d}from"./assets/vendor-DDwt-mbX.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const u=async s=>{const o="47502659-8e710eb0ff3e952458316b5b2",r="https://pixabay.com/api/";try{const n=`${r}?key=${o}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;console.log("Запрос к API:",n);const e=await fetch(n);if(!e.ok)throw new Error(`Ошибка при получении данных: ${e.statusText}`);const t=await e.json();if(console.log("Полученные данные:",t),!t.hits||t.hits.length===0)throw new Error("No images found");return t.hits}catch(n){return console.error(n),[]}},m=s=>{const o=document.querySelector(".gallery");if(o.innerHTML="",console.log("Изображения для отображения:",s),s.length===0){o.innerHTML="<p>No images found</p>";return}const r=s.map(({webformatURL:n,largeImageURL:e,tags:t,likes:i,views:g,comments:y,downloads:h})=>`
      <div class="card">
        <a href="${e}">
          <img src="${n}" alt="${t||"Image"}" />
        </a>
        <p>Likes: ${i} | Views: ${g} | Comments: ${y} | Downloads: ${h}</p>
      </div>
    `).join("");o.insertAdjacentHTML("beforeend",r)},l=document.querySelector("#search-form"),f=document.querySelector(".search-input"),c=document.querySelector(".gallery");l?l.addEventListener("submit",async s=>{s.preventDefault();const o=f.value.trim();if(!o){a.error({message:"Please enter a search term"});return}const r=document.createElement("div");r.classList.add("loader"),r.textContent="Loading...",c.innerHTML="",c.appendChild(r);try{const n=await u(o);n.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!"}):(m(n),new d(".gallery a"))}catch{a.error({message:"Something went wrong, please try again!"})}finally{r&&r.remove()}}):console.log('Элемент с id "search-form" не найден');document.querySelector(".load-more").addEventListener("click",async()=>{const s=f.value.trim();if(!s){a.error({message:"Please enter a search term"});return}const o=document.createElement("div");o.classList.add("loader"),o.textContent="Loading...",c.appendChild(o);try{const r=await u(s);r.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!"}):(m(r),new d(".gallery a"))}catch{a.error({message:"Something went wrong, please try again!"})}finally{const r=document.querySelector(".loader");r&&r.remove()}});
//# sourceMappingURL=index.js.map
