import{i,S as d}from"./assets/vendor-DDwt-mbX.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const f=async n=>{const o="47502659-8e710eb0ff3e952458316b5b2",t="https://pixabay.com/api/";try{const s=`${t}?key=${o}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`,e=await fetch(s);if(!e.ok)throw new Error(`Ошибка при получении данных: ${e.statusText}`);const r=await e.json();if(!r.hits||r.hits.length===0)throw new Error("Нет изображений по запросу");return r.hits}catch(s){return console.error(s),[]}},m=n=>{const o=document.querySelector(".gallery");o.innerHTML="",n.forEach(({webformatURL:t,largeImageURL:s,tags:e,likes:r,views:a,comments:c,downloads:l})=>{const u=`
      <div class="card">
        <a href="${s}">
          <img src="${t}" alt="${e}" />
        </a>
        <p>Likes: ${r} | Views: ${a} | Comments: ${c} | Downloads: ${l}</p>
      </div>
    `;o.insertAdjacentHTML("beforeend",u)})},h=document.querySelector(".search-form"),y=document.querySelector(".search-input"),g=document.querySelector(".gallery");h.addEventListener("submit",async n=>{n.preventDefault();const o=y.value.trim();if(!o){i.error({message:"Please enter a search term"});return}g.innerHTML='<div class="loader">Loading...</div>';try{const t=await f(o);t.length===0?i.info({message:"Sorry, there are no images matching your search query. Please try again!"}):(m(t),new d(".gallery a"))}catch{i.error({message:"Something went wrong, please try again!"})}finally{const t=document.querySelector(".loader");t&&t.remove()}});
//# sourceMappingURL=index.js.map
